"use client"

// ShaderBackground — generated by the 21st.dev Shader Builder
// ("Fluted Glass"). Zero dependencies: one WebGL canvas that fills its parent.
// Adapted from Paper Shaders: https://shaders.paper.design/fluted-glass
// Paper Shaders is licensed under Apache-2.0.
//
// Thravic changes: `colors` swaps the palette live (for light/dark themes) and
// `animate={false}` renders one still frame (for reduced motion).

import { useEffect, useRef } from "react"

type RGB = [number, number, number]

const VERT = `attribute vec2 a_position;
void main() {
  gl_Position = vec4(a_position, 0.0, 1.0);
}`

const FRAG = `#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec3 u_colors[8];
uniform vec4 u_scene;      // resolution.xy, time, colour count
uniform vec4 u_shape;      // scale, intensity, paramA, warp
uniform vec4 u_surface;    // detail, contrast, brightness, saturation
uniform vec4 u_finish;     // hue, vignette, blur, grain
uniform vec4 u_transform;  // seed, rotation, drift, OKLab toggle

#define u_resolution u_scene.xy
#define u_time u_scene.z
#define u_colorCount u_scene.w
#define u_scale u_shape.x
#define u_intensity u_shape.y
#define u_paramA u_shape.z
#define u_contrast u_surface.y
#define u_brightness u_surface.z
#define u_saturation u_surface.w
#define u_vignette u_finish.y
#define u_grain u_finish.w
#ifdef GL_FRAGMENT_PRECISION_HIGH
#define u_seed u_transform.x
#else
#define u_seed mod(u_transform.x, 31.0)
#endif

float hash21(vec2 p) {
#ifndef GL_FRAGMENT_PRECISION_HIGH
  p = mod(p, 31.0);
#endif
  p = fract(p * vec2(234.34, 435.345));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

// Even white noise for film grain (Dave Hoskins hash12)
float grainHash(vec2 p) {
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

float noise(vec2 p) {
  vec2 i = floor(p);
  vec2 f = fract(p);
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(
    mix(hash21(i), hash21(i + vec2(1.0, 0.0)), u.x),
    mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0, 1.0)), u.x),
    u.y);
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p = p * 2.03 + vec2(17.0, 9.2);
    a *= 0.5;
  }
  return v;
}

// Mix through the palette; x is clamped to 0..1. WebGL1 forbids dynamic
// uniform indexing in fragment shaders, hence the constant loop.
vec3 palette(float x) {
  float n = max(u_colorCount - 1.0, 1.0);
  float f = clamp(x, 0.0, 1.0) * n;
  vec3 col = u_colors[0];
  for (int i = 0; i < 7; i++) {
    if (float(i) < n)
      col = mix(col, u_colors[i + 1],
        smoothstep(0.0, 1.0, clamp(f - float(i), 0.0, 1.0)));
  }
  return col;
}

vec3 shade(vec2 p, float t) {
  float flutes = mix(42.0, 7.0, u_paramA);
  float cell = fract((p.x + 1.0) * flutes) - 0.5;
  float prism = sin(cell * 3.1415926) * (0.03 + u_intensity * 0.2);
  vec2 samplePoint = p + vec2(prism, sin(p.x * flutes + t * 0.2) * prism * 0.35);
  float field = fbm(samplePoint * 2.2 + vec2(t * 0.035, -t * 0.025) + u_seed);
  field += 0.24 * sin(samplePoint.y * 3.0 + samplePoint.x * 1.3);
  float highlight = pow(1.0 - abs(cell) * 2.0, mix(12.0, 2.0, u_intensity));
  float shadow = smoothstep(0.18, 0.5, abs(cell));
  vec3 glass = palette(clamp(field + highlight * 0.3, 0.0, 1.0));
  return glass * (0.72 + highlight * 0.42 - shadow * 0.12);
}

void main() {
  vec2 screenUv = gl_FragCoord.xy / u_resolution.xy;
  vec2 p = (gl_FragCoord.xy - 0.5 * u_resolution.xy)
    / min(u_resolution.x, u_resolution.y);
  p *= u_scale;
  vec3 col = shade(p, u_time);
  if (abs(u_contrast - 1.0) > 0.0001)
    col = (col - 0.5) * u_contrast + 0.5;
  if (abs(u_saturation - 1.0) > 0.0001) {
    float luma = dot(col, vec3(0.299, 0.587, 0.114));
    col = mix(vec3(luma), col, u_saturation);
  }
  if (abs(u_brightness) > 0.0001)
    col += u_brightness;
  if (u_vignette > 0.0001) {
    float vd = length(screenUv - 0.5) * 1.41421356;
    col *= 1.0 - u_vignette * smoothstep(0.35, 1.0, vd);
  }
  if (u_grain > 0.0001)
    col += (grainHash(
      gl_FragCoord.xy + vec2(u_seed * 17.0, u_seed * 31.0)) - 0.5) * u_grain;
  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}
`

const UNIFORMS = {
  colors: [
    [0.0627, 0.0627, 0.0627],
    [0.9608, 0.9608, 0.9608],
    [0.6902, 0.6902, 0.6902],
    [0.2275, 0.2275, 0.2275],
  ] as RGB[],
  scale: 1.26,
  intensity: 0.35,
  paramA: 0.28,
  contrast: 1.005,
  brightness: 0,
  saturation: 1,
  vignette: 0,
  grain: 0.042,
  seed: 6867.0,
  timeScale: 0.575,
}

const pendingContextReleases = new WeakMap<HTMLCanvasElement, number>()

// The shader always reads eight colours; pad a shorter palette with its last one.
function packColors(colors: RGB[]) {
  const padded = Array.from({ length: 8 }, (_, i) => colors[Math.min(i, colors.length - 1)])
  return new Float32Array(padded.flat())
}

export function ShaderBackground({
  className,
  colors = UNIFORMS.colors,
  animate = true,
}: {
  className?: string
  /** 2–8 sRGB colours (0–1 channels); swapped live when changed */
  colors?: RGB[]
  /** false renders a single still frame; read on mount */
  animate?: boolean
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const colorsRef = useRef(colors)
  colorsRef.current = colors
  const setColorsRef = useRef<((next: RGB[]) => void) | null>(null)
  const colorsKey = JSON.stringify(colors)

  useEffect(() => {
    setColorsRef.current?.(colorsRef.current)
  }, [colorsKey])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const pendingRelease = pendingContextReleases.get(canvas)
    if (pendingRelease !== undefined) window.clearTimeout(pendingRelease)
    pendingContextReleases.delete(canvas)
    const gl = canvas.getContext("webgl", { antialias: false })
    if (!gl) return

    const compile = (type: number, src: string) => {
      const s = gl.createShader(type)!
      gl.shaderSource(s, src)
      gl.compileShader(s)
      return s
    }
    const program = gl.createProgram()!
    const vertexShader = compile(gl.VERTEX_SHADER, VERT)
    const fragmentShader = compile(gl.FRAGMENT_SHADER, FRAG)
    gl.attachShader(program, vertexShader)
    gl.attachShader(program, fragmentShader)
    gl.linkProgram(program)
    gl.deleteShader(vertexShader)
    gl.deleteShader(fragmentShader)
    gl.useProgram(program)

    const buf = gl.createBuffer()
    gl.bindBuffer(gl.ARRAY_BUFFER, buf)
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW)
    const loc = gl.getAttribLocation(program, "a_position")
    gl.enableVertexAttribArray(loc)
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0)

    const uni = {
      colors: gl.getUniformLocation(program, "u_colors"),
      scene: gl.getUniformLocation(program, "u_scene"),
      shape: gl.getUniformLocation(program, "u_shape"),
      surface: gl.getUniformLocation(program, "u_surface"),
      finish: gl.getUniformLocation(program, "u_finish"),
      transform: gl.getUniformLocation(program, "u_transform"),
    }
    let colorCount = colorsRef.current.length
    gl.uniform3fv(uni.colors, packColors(colorsRef.current))
    gl.uniform4f(uni.shape, UNIFORMS.scale, UNIFORMS.intensity, UNIFORMS.paramA, 0)
    gl.uniform4f(uni.surface, 0, UNIFORMS.contrast, UNIFORMS.brightness, UNIFORMS.saturation)
    gl.uniform4f(uni.finish, 0, UNIFORMS.vignette, 0, UNIFORMS.grain)
    gl.uniform4f(uni.transform, UNIFORMS.seed, 0, 0, 0)

    let bounds = canvas.getBoundingClientRect()
    let raf = 0
    let visible = document.visibilityState === "visible"
    let inView = true
    let disposed = false
    const start = performance.now()
    const timeScale = animate ? UNIFORMS.timeScale : 0

    const resizeCanvas = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2)
      const rawWidth = Math.max(1, Math.round(bounds.width * dpr))
      const rawHeight = Math.max(1, Math.round(bounds.height * dpr))
      const pixelScale = Math.min(1, Math.sqrt(2_000_000 / Math.max(1, rawWidth * rawHeight)))
      const width = Math.max(1, Math.round(rawWidth * pixelScale))
      const height = Math.max(1, Math.round(rawHeight * pixelScale))
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width
        canvas.height = height
        gl.viewport(0, 0, width, height)
      }
    }

    function requestRender() {
      if (!disposed && visible && inView && raf === 0) raf = requestAnimationFrame(render)
    }

    setColorsRef.current = (next: RGB[]) => {
      colorCount = next.length
      gl.uniform3fv(uni.colors, packColors(next))
      requestRender()
    }

    const updateLayout = () => {
      bounds = canvas.getBoundingClientRect()
      resizeCanvas()
      requestRender()
    }
    window.addEventListener("resize", updateLayout)
    const resizeObserver = new ResizeObserver(updateLayout)
    resizeObserver.observe(canvas)

    const pause = () => {
      if (raf !== 0) {
        cancelAnimationFrame(raf)
        raf = 0
      }
    }
    const intersectionObserver = new IntersectionObserver(([entry]) => {
      inView = entry?.isIntersecting ?? true
      if (inView) requestRender()
      else pause()
    })
    intersectionObserver.observe(canvas)
    const onVisibilityChange = () => {
      visible = document.visibilityState === "visible"
      if (visible) requestRender()
      else pause()
    }
    document.addEventListener("visibilitychange", onVisibilityChange)

    const render = (now: number) => {
      raf = 0
      if (disposed || !visible || !inView) return
      resizeCanvas()
      gl.uniform4f(uni.scene, canvas.width, canvas.height, ((now - start) / 1000) * timeScale, colorCount)
      gl.drawArrays(gl.TRIANGLES, 0, 3)
      if (timeScale !== 0) requestRender()
    }
    requestRender()

    return () => {
      disposed = true
      setColorsRef.current = null
      cancelAnimationFrame(raf)
      resizeObserver.disconnect()
      intersectionObserver.disconnect()
      document.removeEventListener("visibilitychange", onVisibilityChange)
      window.removeEventListener("resize", updateLayout)
      gl.deleteBuffer(buf)
      gl.deleteProgram(program)
      // Deferred so a StrictMode remount can reuse the context
      const releaseTimer = window.setTimeout(() => {
        if (pendingContextReleases.get(canvas) !== releaseTimer) return
        pendingContextReleases.delete(canvas)
        gl.getExtension("WEBGL_lose_context")?.loseContext()
        canvas.width = 1
        canvas.height = 1
      }, 0)
      pendingContextReleases.set(canvas, releaseTimer)
    }
    // animate is read once on mount by design
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return <canvas ref={canvasRef} className={className} style={{ display: "block", width: "100%", height: "100%" }} />
}
